import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { escapeHtml, html, isSafeHtml, joinHtml, safe, toHtml } from "../js/core/html.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// ------------------------------------------------------------------ escaping

test("the five characters that change how markup parses are escaped", () => {
  assert.equal(escapeHtml(`<&>"'`), "&lt;&amp;&gt;&quot;&#39;");
});

test("ampersands are escaped once, not twice", () => {
  // & has to be replaced first or "&lt;" comes back out as "&amp;lt;".
  assert.equal(escapeHtml("<"), "&lt;");
  assert.equal(escapeHtml("&lt;"), "&amp;lt;");
});

test("nothing renders as the empty string, not as the word for nothing", () => {
  assert.equal(escapeHtml(null), "");
  assert.equal(escapeHtml(undefined), "");
  // A real zero is a value and must survive.
  assert.equal(escapeHtml(0), "0");
});

test("a script tag in a value comes out as text", () => {
  const cid = '<script src="https://evil.example/x.js"></script>';
  const out = html`<i class="fa-solid fa-box"></i>${cid}`.value;
  assert.ok(!out.includes("<script"), out);
  assert.ok(out.includes("&lt;script"), out);
  // The markup the author wrote is still markup.
  assert.ok(out.includes('<i class="fa-solid fa-box"></i>'));
});

test("a value cannot break out of the attribute it is interpolated into", () => {
  // The transaction hash goes inside href="…" on both result pages. A value
  // carrying a double quote would otherwise close the attribute and start
  // writing its own.
  const txHash = '" onmouseover="steal()" x="';
  const out = html`<a href="https://explorer.example/tx/${txHash}">tx</a>`.value;
  assert.ok(!out.includes('onmouseover="steal()"'), out);
  assert.equal(out.split('"').length - 1, 2, `exactly one quoted attribute: ${out}`);
});

// ------------------------------------------------------------------- nesting

test("a safe fragment passes through another template intact", () => {
  const hint = safe("Set <code>contract.rpcUrl</code>.");
  const out = html`Nothing is confirmed. ${hint}`.value;
  assert.equal(out, "Nothing is confirmed. Set <code>contract.rpcUrl</code>.");
});

test("a string that merely looks safe does not pass through", () => {
  // The whole point: passing through is a property of a value this code
  // built, not of what the characters in it happen to be.
  const pretending = { value: "<b>hello</b>", toString: () => "<b>hello</b>" };
  assert.equal(isSafeHtml(pretending), false);
  assert.equal(html`${pretending}`.value, "&lt;b&gt;hello&lt;/b&gt;");
});

test("toHtml escapes anything that is not a safe value", () => {
  assert.equal(toHtml("<b>"), "&lt;b&gt;");
  assert.equal(toHtml(safe("<b>")), "<b>");
  assert.equal(toHtml(html`<b>${"<i>"}</b>`), "<b>&lt;i&gt;</b>");
});

test("joining fragments keeps them safe, and refuses anything else", () => {
  const cards = [html`<b>${"<x>"}</b>`, html`<i>${"&"}</i>`];
  assert.equal(toHtml(joinHtml(cards)), "<b>&lt;x&gt;</b><i>&amp;</i>");
  // A raw string in the list is the mistake this exists to catch: escaping it
  // silently would render markup as text, trusting it would be the hole.
  assert.throws(() => joinHtml([html`<b>ok</b>`, "<b>raw</b>"]), TypeError);
});

// ------------------------------------------------------- the sinks themselves

/*
 * Escaping one page is worth little if the next value someone renders skips
 * it, so the shape of every sink is checked rather than the behaviour of the
 * ones that exist today. An assignment to innerHTML may be one of four
 * things: a tagged template, a value that went through toHtml(), the empty
 * string, or a quoted literal with nothing interpolated into it. Anything
 * else is a new hole and this fails on it.
 *
 * Deliberately a source check and not a runtime one. The bug it guards
 * against is a call site written in six months, which no runtime test of
 * today's call sites can see.
 */
const SINK = /\.(innerHTML|outerHTML)\s*=\s*([^\n;]+)/g;

function clientSources() {
  const dir = path.join(ROOT, "js");
  const found = [];
  const walk = (at) => {
    for (const entry of fs.readdirSync(at, { withFileTypes: true })) {
      const full = path.join(at, entry.name);
      // Vendored third-party builds are not ours to rewrite; they are
      // regenerated by `npm run vendor` and reviewed as a whole.
      if (entry.isDirectory()) {
        if (entry.name !== "vendor") walk(full);
      } else if (entry.name.endsWith(".js") && !entry.name.endsWith(".min.js")) {
        found.push(full);
      }
    }
  };
  walk(dir);
  return found;
}

test("every innerHTML in the client goes through the escaping", () => {
  const offenders = [];
  for (const file of clientSources()) {
    const source = fs.readFileSync(file, "utf8");
    const lines = source.split("\n");
    for (const match of source.matchAll(SINK)) {
      const rhs = match[2].trim();
      const ok =
        rhs.startsWith("html`") ||
        rhs.startsWith("toHtml(") ||
        rhs === '""' ||
        rhs === "''" ||
        // A literal with no interpolation is markup this file's author wrote.
        (/^['"]/.test(rhs) && !rhs.includes("${"));
      if (!ok) {
        const line = source.slice(0, match.index).split("\n").length;
        offenders.push(`${path.relative(ROOT, file)}:${line}: ${lines[line - 1].trim()}`);
      }
    }
  }
  assert.deepEqual(offenders, [], `untagged markup sink:\n${offenders.join("\n")}`);
});

test("the scan would notice an untagged sink", () => {
  // The check above passes trivially if the regex matches nothing, so prove
  // it matches the thing it is looking for.
  const bad = 'node.innerHTML = `<b>${cid}</b>`;';
  const matches = [...bad.matchAll(SINK)];
  assert.equal(matches.length, 1);
  assert.ok(!matches[0][2].trim().startsWith("html`"));
});

test("the scan reads the files it thinks it reads", () => {
  const files = clientSources().map((file) => path.relative(ROOT, file));
  assert.ok(files.includes("js/chunked-app.js"), files.join(", "));
  assert.ok(files.includes("js/core/html.js"));
  assert.ok(
    files.every((file) => !file.includes("vendor/")),
    files.join(", ")
  );
});
