#!/usr/bin/env node
/**
 * Copy the @noble modules the frontend uses into js/vendor/noble/, rewriting
 * their imports so a browser can follow them.
 *
 * The pages load ES modules with no bundler, which works for our own code
 * because it imports by relative path. @noble's published ESM does not: its
 * modules import each other by package specifier — `@noble/hashes/crypto`,
 * `@noble/ciphers/utils` — which Node resolves through the package's
 * "exports" field and a browser cannot resolve at all. Importing
 * node_modules/@noble/hashes/esm/argon2.js from a page therefore fails the
 * whole module graph with "Failed to resolve module specifier", taking
 * chunking, sealing, upload, retrieval and verification down together.
 *
 * The browser's answer to that is an import map, but an import map has to be
 * inline and the gateway serves a Content-Security-Policy with no
 * 'unsafe-inline', so it is refused. Copying the modules in and making the
 * imports relative needs neither an inline script nor a weaker CSP, and it is
 * what this repository already does with its other third-party browser code
 * (js/bootstrap.min.js, js/qrcode.min.js, js/aos.js).
 *
 * The output is generated, not edited: run `npm run vendor` after changing a
 * @noble version, and CI regenerates and diffs so it cannot drift from the
 * installed package.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "js", "vendor", "noble");

/**
 * What the frontend actually enters through. Everything else is copied
 * because one of these reaches it, so the vendored tree stays the reachable
 * set rather than a whole package.
 */
const ENTRIES = [
  { package: "@noble/hashes", entry: "argon2.js", importedBy: "js/core/kdf.js" },
  { package: "@noble/ciphers", entry: "chacha.js", importedBy: "js/core/suites.js" },
];

const IMPORT = /(\bfrom\s*|\bimport\s*\(\s*)(['"])([^'"]+)\2/g;
const SOURCE_MAP_COMMENT = /\n?\/\/# sourceMappingURL=.*$/m;

function esmDirectory(pkg) {
  return path.join(ROOT, "node_modules", pkg, "esm");
}

function packageVersion(pkg) {
  const manifest = path.join(ROOT, "node_modules", pkg, "package.json");
  return JSON.parse(fs.readFileSync(manifest, "utf8")).version;
}

/**
 * Rewrite one module's imports to relative paths within the vendored package,
 * and report which files it pulls in.
 */
function rewrite(source, pkg) {
  const referenced = [];
  const rewritten = source.replace(IMPORT, (match, keyword, quote, specifier) => {
    let file;
    if (specifier.startsWith("./") || specifier.startsWith("../")) {
      // normalize() strips a leading "./", which would turn a relative
      // import back into the bare specifier this script exists to remove.
      const normalized = path.posix.normalize(specifier);
      file = normalized.startsWith(".") ? normalized : `./${normalized}`;
    } else if (specifier.startsWith(`${pkg}/`)) {
      // `@noble/hashes/crypto` and `./crypto.js` are the same module; the
      // first form is what a browser cannot resolve.
      file = `./${specifier.slice(pkg.length + 1)}.js`;
    } else {
      // A Node builtin ("node:crypto") in a branch the browser never takes.
      // Left alone: rewriting it would be a lie, and nothing we copy has one.
      return match;
    }
    referenced.push(file.replace(/^\.\//, ""));
    return `${keyword}${quote}${file}${quote}`;
  });

  return { source: rewritten, referenced };
}

function collect(pkg) {
  const directory = esmDirectory(pkg);
  if (!fs.existsSync(directory)) {
    throw new Error(`${pkg} is not installed — run \`npm install\` first`);
  }

  const files = new Map();
  const queue = ENTRIES.filter((e) => e.package === pkg).map((e) => e.entry);

  while (queue.length > 0) {
    const name = queue.shift();
    if (files.has(name)) continue;

    const from = path.join(directory, name);
    if (!fs.existsSync(from)) throw new Error(`${pkg} has no esm/${name}`);

    const { source, referenced } = rewrite(fs.readFileSync(from, "utf8"), pkg);
    files.set(name, source);
    for (const next of referenced) if (!files.has(next)) queue.push(next);
  }

  return files;
}

function header(pkg, version, name) {
  return (
    `/*\n` +
    ` * Vendored from ${pkg}@${version} (esm/${name}), MIT licensed.\n` +
    ` * Generated by scripts/vendor-noble.mjs — do not edit; run \`npm run vendor\`.\n` +
    ` * Only the package-specifier imports are changed, so a browser can resolve them.\n` +
    ` */\n`
  );
}

function writeTree() {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const summary = [];

  for (const pkg of [...new Set(ENTRIES.map((e) => e.package))]) {
    const version = packageVersion(pkg);
    const shortName = pkg.split("/")[1];
    const target = path.join(OUT, shortName);
    fs.mkdirSync(target, { recursive: true });

    const files = collect(pkg);
    for (const [name, source] of [...files].sort(([a], [b]) => (a < b ? -1 : 1))) {
      const body = source.replace(SOURCE_MAP_COMMENT, "").trimEnd();
      fs.writeFileSync(path.join(target, name), `${header(pkg, version, name)}${body}\n`);
    }

    const license = path.join(ROOT, "node_modules", pkg, "LICENSE");
    if (fs.existsSync(license)) {
      fs.copyFileSync(license, path.join(target, "LICENSE"));
    }

    summary.push({ pkg, version, shortName, count: files.size });
  }

  const readme =
    `# Vendored @noble modules\n\n` +
    `Generated by \`scripts/vendor-noble.mjs\`. Do not edit these files; run\n` +
    `\`npm run vendor\` after changing a @noble version and commit the result.\n\n` +
    `@noble's published ESM imports its own modules by package specifier, which\n` +
    `a browser cannot resolve and an import map cannot fix here, because the\n` +
    `gateway's Content-Security-Policy has no \`'unsafe-inline'\`. These copies\n` +
    `differ from upstream only in those specifiers, which are made relative.\n\n` +
    `Each package is MIT licensed; its LICENSE is copied alongside the code.\n\n` +
    summary
      .map(
        (s) =>
          `- \`${s.shortName}/\` — ${s.count} file(s) from ${s.pkg}@${s.version}, reachable from ` +
          ENTRIES.filter((e) => e.package === s.pkg)
            .map((e) => `\`esm/${e.entry}\` (imported by \`${e.importedBy}\`)`)
            .join(" and ")
      )
      .join("\n") +
    `\n`;

  fs.writeFileSync(path.join(OUT, "README.md"), readme);

  for (const s of summary) {
    console.log(`${s.shortName}: ${s.count} file(s) from ${s.pkg}@${s.version}`);
  }
}

writeTree();
